# Auto-generated by Executor — do not edit manually
# Plan: eco, Iteration: 1, Plan index: 3

# --- Load technology ---
source $env(PDK_PREAMBLE)

# --- Load design ---
read_db  $env(INPUT_DB)
read_sdc $env(SDC_FILE)
source   $env(SETRC_TCL)

# Don't-use list — mirror of ORFS asap7 config.mk DONT_USE_CELLS. Applied AFTER
# read_db (set_dont_use needs a linked design) and BEFORE repair_timing so the
# resizer cannot size into forbidden fractional-drive cells. The ORFS
# DONT_USE_CELLS env var is not propagated to this standalone OpenROAD process.
set_dont_use { *x1p*_ASAP7* *xp*_ASAP7* SDF* ICG* }

# --- Load eco_insert_buffer proc ---
source Scripts/tcl/eco_buf_insert.tcl

# --- Directed ECO changes ---
eco_insert_buffer {_047_} {_590_/SN} BUFx4_ASAP7_75t_SL buf_ha590_eco -at driver -in_pin A -out_pin Y 
eco_insert_buffer {_029_} {_584_/SN} BUFx4_ASAP7_75t_SL buf_ha584_eco -at driver -in_pin A -out_pin Y 
eco_insert_buffer {_041_} {_588_/SN} BUFx4_ASAP7_75t_SL buf_ha588_eco -at driver -in_pin A -out_pin Y 

# --- Legalize and re-estimate parasitics ---
detailed_placement
check_placement -verbose
estimate_parasitics -placement

# --- Placement report (POST-LEGALIZATION, BEFORE GR) ---
set placement_report_skip_load 1
source Scripts/tcl/generate_placement_report.tcl

# --- Write HANDOFF database (PRE-GR state) ---
write_db  $env(OUTPUT_DB)
write_sdc [file join $env(OUTPUT_DIR) output.sdc]

# --- Global route (Blocks A-D) ---
# Block A — optional pre-GR hook
if {[info exists ::env(PRE_GLOBAL_ROUTE_TCL)] && [file exists $::env(PRE_GLOBAL_ROUTE_TCL)]} {
    source $::env(PRE_GLOBAL_ROUTE_TCL)
}
set _res_aware {}
if {[info exists ::env(ENABLE_RESISTANCE_AWARE)] && $::env(ENABLE_RESISTANCE_AWARE) ne ""} {
    set _res_aware [list -resistance_aware 0]
}

# Configure routing layers — must be set after every read_db/write_db
if {[info exists ::env(MIN_ROUTING_LAYER)] && $::env(MIN_ROUTING_LAYER) ne ""     && [info exists ::env(MAX_ROUTING_LAYER)] && $::env(MAX_ROUTING_LAYER) ne ""} {
    set _layer_range "$::env(MIN_ROUTING_LAYER)-$::env(MAX_ROUTING_LAYER)"
    set_routing_layers -signal $_layer_range
    set _adj "0.5"
    if {[info exists ::env(ROUTING_LAYER_ADJUSTMENT)] && $::env(ROUTING_LAYER_ADJUSTMENT) ne ""} {
        set _adj $::env(ROUTING_LAYER_ADJUSTMENT)
    }
    set_global_routing_layer_adjustment $_layer_range $_adj
}

# Block B — pin access
pin_access

# Block C — global_route (catch GRT-0116 on congested designs)
set _gr_extra {}
if {[info exists ::env(GLOBAL_ROUTE_ARGS)] && $::env(GLOBAL_ROUTE_ARGS) ne ""} {
    set _gr_extra $::env(GLOBAL_ROUTE_ARGS)
}
if {[catch {
    global_route \
        -congestion_report_file [file join $env(OUTPUT_DIR) congestion.rpt] \
        -verbose \
        {*}$_gr_extra {*}$_res_aware
} _gr_err]} {
    puts "WARNING: global_route raised: $_gr_err"
    puts "WARNING: continuing with measurement — guides still usable."
}

# Block D — propagated clock + GR-aware parasitics
if {[info exists ::env(CELL_PAD_IN_SITES_DETAIL_PLACEMENT)] && $::env(CELL_PAD_IN_SITES_DETAIL_PLACEMENT) ne ""} {
    set_placement_padding -global \
        -left  $::env(CELL_PAD_IN_SITES_DETAIL_PLACEMENT) \
        -right $::env(CELL_PAD_IN_SITES_DETAIL_PLACEMENT)
}
set_propagated_clock [all_clocks]
estimate_parasitics -global_routing

# --- Extract artifacts (POST-GR) ---
set generate_design_artifacts_skip_load 1
source Scripts/tcl/generate_design_artifacts.tcl
